zlbbs32/apps/cms/__init__.py
# -*- coding: utf-8 -*-
import apps.cms.hooks

if __name__ == '__main__':
    print
    1

zlbbs32/apps/cms/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint,render_template,views,request,redirect,url_for,session,g,jsonify
from apps.cms.forms import LoginForm,ResetpwdForm,ResetemailForm,AddBannerForm,UpdateBannerForm,AddBoardForm,UpdateBoardForm
from apps.cms.models import CMSUser,CMPermission
from apps.models import BannersModel,BoardModel,PostModel,HighlightPostModel
import config
from apps.cms.decorators import LoginRequired,permission_required
from exts import db,mail
from utils import zlmemcache
from flask_mail import Message
import string
import random
from tasks import send_email

# 定义 cms 的蓝图
cms_bp = Blueprint('cms',__name__,url_prefix='/cms')

# cms 首页
@cms_bp.route('/index/')
def index():
    return render_template('/cms/cms_index.html')

# cms 注销
@cms_bp.route('/logout/')
@LoginRequired
def logout():
    session.pop(config.CMS_USER_ID)
    return redirect(url_for('cms.login'))


# cms 个人中心
@cms_bp.route('/profile/')
@LoginRequired
def profile():

    return render_template('cms/cms_profile.html')


# cms 给指定邮箱发送验证码（ajax 调用）
@cms_bp.route('/sendcaptcha/')
def sendcaptcha():

    #/cms/sendcaptcha/?email=1010784344@qq.com

    # 获取邮箱（给谁发）
    email = request.args.get('email')
    if not email:
        return jsonify({'code': '400', 'message': '请输入邮箱！'})
    else:


        # 获取验证码（内容）
        allcaptcha = list(string.ascii_letters)
        allcaptcha.extend(map(lambda x:str(x),range(0,10)))
        captcha = ''.join(random.sample(allcaptcha,6))

        print(email,captcha)

        # 储存验证码到内存中（memcached）
        zlmemcache.set(email,captcha)

        #发送验证码

        # # celery异步前
        # message = Message('王者荣耀论坛邮箱验证码', recipients=[email], body='您的邮箱验证码是：%s'%captcha)
        # try:
        #     mail.send(message)
        # except:
        #     return jsonify({'code': '400', 'message': '网络错误！'})

        # celery异步后触发任务
        send_email.delay('王者荣耀论坛邮箱验证码', recipients=[email], body='您的邮箱验证码是：%s' % captcha)


        return jsonify({'code': '200', 'message': '验证码已经发送至您的邮箱，请确认！'})



# 发送邮件测试
@cms_bp.route('/emailbug/')
def emailbug():
    # 邮件主题，收件人列表，邮件正文
    message = Message('邮件发送',recipients=['1010784344@qq.com'],body='测试')
    mail.send(message)
    return 'success'


# 轮播图管理（这里就不添加权限验证了）
@cms_bp.route('/banners/')
@LoginRequired
def banners():

    # allbanner = BannersModel.query.all()
    # 按照权重倒叙排列
    allbanner = BannersModel.query.order_by(BannersModel.priority.desc()).all()

    return render_template('cms/cms_banners.html',allbanner=allbanner)



#添加轮播图弹窗 的提交表单
@cms_bp.route('/abanner/',methods = ['POST'])
@LoginRequired
def abanner():

    form = AddBannerForm(request.form)

    if form.validate():
        name = form.name.data
        img_url = form.img_url.data
        link_url = form.link_url.data
        priority = form.priority.data

        banner = BannersModel(name=name, image_url=img_url,link_url=link_url, priority=priority)

        db.session.add(banner)
        db.session.commit()

        return jsonify({'code': '200', 'message': '轮播图添加成功！'})
    else:

        message = form.errors.popitem()[1][0]
        # 表单验证错误（数据格式不对）

        return jsonify({'code': '400', 'message': message})




#编辑轮播图弹窗 的提交表单
@cms_bp.route('/ubanner/',methods = ['POST'])
@LoginRequired
def ubanner():

    form = UpdateBannerForm(request.form)

    if form.validate():
        name = form.name.data
        img_url = form.img_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        bannerid = form.banner_id.data

        banner = BannersModel.query.get(bannerid)

        if banner:
            banner.name = name
            banner.img_url = img_url
            banner.link_url = link_url
            banner.priority = priority

            # db.session.add(banner)
            db.session.commit()

            return jsonify({'code': '200', 'message': '轮播图编辑成功！'})
        else:
            return jsonify({'code': '400', 'message': '轮播图不存在！'})
    else:

        message = form.errors.popitem()[1][0]
        # 表单验证错误（数据格式不对）

        return jsonify({'code': '400', 'message': message})


#删除轮播图弹窗 的提交表单
@cms_bp.route('/dbanner/',methods = ['POST'])
@LoginRequired
def dbanner():

    bannerid = request.form.get('banner_id')

    if not bannerid:
        return jsonify({'code': '400', 'message': '轮播图id不存在！'})


    banner = BannersModel.query.get(bannerid)
    if not banner:
        return jsonify({'code': '400', 'message': '轮播图不存在！'})


    db.session.delete(banner)
    db.session.commit()
    return jsonify({'code': '200', 'message': '轮播图删除成功！'})





# 帖子管理
@cms_bp.route('/posts/')
@LoginRequired
@permission_required(CMPermission.POSTER)
def posts():
    all_post = PostModel.query.all()
    return render_template('cms/cms_posts.html',all_post=all_post)


# 帖子加精
@cms_bp.route('/hpost/',methods = ['POST'])
@LoginRequired
@permission_required(CMPermission.POSTER)
def hpost():

    # post_id = request.args.get('post_id')
    post_id = request.form.get('post_id')

    if not post_id:
        return jsonify({'code': '400', 'message': '请输入帖子id！'})

    post = PostModel.query.get(post_id)

    if not post:
        return jsonify({'code': '400', 'message': '帖子不存在！'})

    highlight = HighlightPostModel()
    highlight.posts = post

    db.session.add(highlight)
    db.session.commit()

    return jsonify({'code': '200', 'message': '帖子加精成功！'})



# 帖子取消加精
@cms_bp.route('/uhpost/',methods = ['POST'])
@LoginRequired
@permission_required(CMPermission.POSTER)
def uhpost():

    post_id = request.form.get('post_id')

    if not post_id:
        return jsonify({'code': '400', 'message': '请输入帖子id！'})

    # 帖子取消加精，这里其实并没有用到 post 这个对象，只是用这个对象去看帖子是否存在而已
    post = PostModel.query.get(post_id)
    if not post:
        return jsonify({'code': '400', 'message': '帖子不存在！'})

    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()

    db.session.delete(highlight)
    db.session.commit()

    return jsonify({'code': '200', 'message': '帖子取消加精成功！'})









# 评论管理
@cms_bp.route('/comments/')
@LoginRequired
@permission_required(CMPermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')



# 板块管理
@cms_bp.route('/boards/')
@LoginRequired
@permission_required(CMPermission.BOARDER)
def boards():
    all_boards = BoardModel.query.all()
    return render_template('cms/cms_boards.html',boards = all_boards)


# 添加板块
@cms_bp.route('/aboards/', methods=['POST'])
@LoginRequired
@permission_required(CMPermission.BOARDER)
def aboards():

    form = AddBoardForm(request.form)

    if form.validate():
        name = form.name.data

        board = BoardModel(name=name)

        db.session.add(board)
        db.session.commit()

        return jsonify({'code': '200', 'message': '板块添加成功！'})
    else:

        # 表单验证错误（数据格式不对）
        message = form.errors.popitem()[1][0]

        return jsonify({'code': '400', 'message': message})



# 更新板块
@cms_bp.route('/uboards/', methods=['POST'])
@LoginRequired
@permission_required(CMPermission.BOARDER)
def uboards():

    form = UpdateBoardForm(request.form)

    if form.validate():
        name = form.name.data
        boardid = form.board_id.data

        banner = BannersModel.query.get(boardid)

        if banner:
            banner.name = name

            db.session.commit()

            return jsonify({'code': '200', 'message': '板块编辑成功！'})
        else:
            return jsonify({'code': '400', 'message': '板块不存在！'})
    else:
        # 表单验证错误（数据格式不对）
        message = form.errors.popitem()[1][0]

        return jsonify({'code': '400', 'message': message})




# 删除板块
@cms_bp.route('/dboards/', methods=['POST'])
@LoginRequired
@permission_required(CMPermission.BOARDER)
def dboards():

    # 没有经过验证直接获取数据的方式
    boardid = request.form.get('board_id')

    if not boardid:
        return jsonify({'code': '400', 'message': '板块id不存在！'})

    # board = BoardModel.query.filter_by(id=boardid).first()
    board = BoardModel.query.get(boardid)

    if not board:
        return jsonify({'code': '400', 'message': '板块不存在！'})

    db.session.delete(board)
    db.session.commit()
    return jsonify({'code': '200', 'message': '板块删除成功！'})


# 前台用户管理
@cms_bp.route('/fusers/')
@LoginRequired
@permission_required(CMPermission.FRONTUSER)
def fusers():
    return render_template('cms/cms_fusers.html')



# CMS用户管理
@cms_bp.route('/cusers/')
@LoginRequired
@permission_required(CMPermission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')




# CMS组管理
@cms_bp.route('/croles/')
@LoginRequired
@permission_required(CMPermission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')




# cms 登录
# 基于调度方法的类视图
class Login_View(views.MethodView):
    def get(self,message=None):
        # 渲染具有层级目录的书写方法
        return render_template('cms/cms_login.html',message=message)
    def post(self):
        # 将页面提交的数据导入 wtforms 进行验证
        form = LoginForm(request.form)

        email = form.email.data
        password = form.password.data
        remember = form.remember.data

        if form.validate():
            user = CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):

                session[config.CMS_USER_ID] = user.id

                # 对应页面的 remember me 功能
                # 如果设置 session.permanet = True，那么过期时间是 31天
                if remember:
                    session.permanent = True

                # 蓝图使用 url_for ，记得把蓝图的名字给加上。
                # 使用 url_for 反转蓝图的普通视图函数
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='邮箱或者密码错误')
                # return render_template('/cms/cms_login.html', message='邮箱或者密码错误')

        else:
            # 返回具体的错误验证信息
            # form.errors : {'password': ['请输入正确格式的密码']}
            message = form.errors.popitem()[1][0]
            # 表单验证错误（数据格式不对）
            return self.get(message=message)

zlbbs32/apps/front/views.py
# -*- coding: utf-8 -*-
# from apps.front import bp
from flask import Blueprint,views,render_template,request,jsonify,session,url_for,g,abort
from apps.front.forms import SignupForm,SigninForm,AddPostForm,AddCommentForm
from apps.models import BannersModel,BoardModel,PostModel,CommentModel,HighlightPostModel
from apps.front.models import FrontUser
from apps.front.decorators import LoginRequired
from exts import alidayu,db
from utils import safeutils
import config
from flask_paginate import Pagination,get_page_parameter

from sqlalchemy import func

front_bp = Blueprint('front',__name__)

# 测试：注册完成跳转回上一个页面
@front_bp.route('/test/')
def test():
    return render_template('test.html')


@front_bp.route('/')
def index():
    # 轮播图展示
    banners = BannersModel.query.order_by(BannersModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()

    # 排序信息(当没有st赋值，默认为 1 ，也就是当为首页时，st=1)
    st = request.args.get('st',type=int,default=1)

    # 分页前
    # posts = PostModel.query.all()

    # 分页后
    # 从 url 的查询参数获取当前是第几页(指定当前是第几页)
    page = request.args.get(get_page_parameter(),type=int,default=1)

    start = (page-1)*config.PER_PAGE
    end = start + config.PER_PAGE

    # 选中的板块
    bd = request.args.get('bd', type=int, default=None)
    total = 0
    query_obj = None

    # 最新帖排序
    if st == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    # 精华帖排序(左连接)
    if st == 2:
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(HighlightPostModel.create_time.desc(),PostModel.create_time.desc())
    # 点赞最多排序（功能还没有实现，暂时跟最新帖是一样的）
    if st == 3:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    # 评论最多排序
    if st == 4:
        # 按一个帖子下面评论的多少来给这些帖子进行排序
        # 先把评论按帖子来进行分组，然后再根据评论的个数进行排序（需要多多进行学习）
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).\
            order_by(func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    # 获取指定页的数据
    if bd:
        posts = query_obj.filter(PostModel.board_id == bd).slice(start,end)
        total = query_obj.filter(PostModel.board_id == bd).count()
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()

    # pagination 用于前台页面的上一页和下一页的控制
    pagination = Pagination(bs_version=3, page=page,total=total)


    # 返回多个参数到 html 页面
    context = {'banners':banners,
               'boards': boards,
               'posts': posts,
               'pagination':pagination,
               # 方便前端点击那个板块，那个板块就选中的参数
               'current_board':bd,
               'current_st':st

               }


    return render_template('front/front_index.html',**context)


# 测试：短信验证测试接口(其他方面都正常，就接口有问题（appkey-not-exists），暂时放过)
# 阿里云账号：ali1010784344   密码：cwx364505

@front_bp.route('/sms_captcha/')
def sms_captcha():
    result = alidayu.send_sms('18735934287',code='abcd')
    if result:
        print('发送成功')
    else:
        print('发送失败')


# 发布帖子
@front_bp.route('/apost/',methods=['GET','POST'])
@LoginRequired
def apost():

    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html',boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data


            board = BoardModel.query.get(board_id)


            if not board:
                return jsonify({'code': '400', 'message': '没有这个板块！'})
            else:
                post = PostModel(title=title,content=content)
                post.boards = board
                # 帖子新增用户名
                post.author = g.front_user

                db.session.add(post)
                db.session.commit()

                return jsonify({'code': '200', 'message': '帖子发布成功！'})

        else:
            message = form.errors.popitem()[1][0]
            # 表单验证错误（数据格式不对）

            return jsonify({'code': '400', 'message': message})


# 帖子详情
@front_bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)

    if not post:
        #如果帖子不存在，手动抛出一个异常
        abort(404)
    else:
        return render_template('front/front_pdetail.html',post=post)




# 发表评论
@front_bp.route('/acomment/',methods=['POST'])
@LoginRequired
def acomment():

    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data

        post = PostModel.query.get(post_id)

        if not post:
            return jsonify({'code': '400', 'message': '没有这个帖子！'})
        else:
            comment = CommentModel(content=content)
            comment.posts = post
            comment.author = g.front_user

            db.session.add(comment)
            db.session.commit()

            return jsonify({'code': '200', 'message': '帖子发布成功！'})

    else:
        message = form.errors.popitem()[1][0]
        # 表单验证错误（数据格式不对）

        return jsonify({'code': '400', 'message': message})





class SignupView(views.MethodView):

    def get(self):
        # 获取上一个页面的 url
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html',return_to=return_to)
        else:
            return render_template('front/front_signup.html')
    def post(self):
        form = SignupForm(request.form)

        if form.validate():
            # telephone = form.telephone.data
            username = form.username.data
            password = form.password.data
            user = FrontUser(username=username,password=password)
            db.session.add(user)
            db.session.commit()

            return jsonify({'code': '200', 'message': '用户注册成功！'})
        else:

            message = form.errors.popitem()[1][0]
            # 表单验证错误（数据格式不对）

            return jsonify({'code': '400', 'message': message})


class SigninView(views.MethodView):

    def get(self):
        # 获取上一个页面的 url
        return_to = request.referrer
        # 不能跳转到本页面及注册页面
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(return_to):
            return render_template('front/front_signin.html',return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        password = form.password.data

        print(password)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remeber = form.remember.data

            print(password)

            user = FrontUser.query.filter_by(telephone=telephone).first()

            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remeber:
                    session.permanent = True
                return jsonify({'code': '200', 'message': '用户登录成功！'})
            else:

                return jsonify({'code': '400', 'message': '用户手机或者密码错误！'})
        else:
            message = form.errors.popitem()[1][0]
            # 表单验证错误（数据格式不对）
            return jsonify({'code': '400', 'message': message})







front_bp.add_url_rule('/signup/',view_func=SignupView.as_view('signup'))
front_bp.add_url_rule('/signin/',view_func=SigninView.as_view('signin'))

zlbbs32/templates/cms/cms_base.html
{% from "common/_macros.html" import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {#第一步 在模板的meta 标签中渲染（设置）一个 csrf-token#}
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}

    {% endblock %}</title>

    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

    {#    前端弹窗提示sweetalert#}
    <link href="{{ static('common/sweetalert/sweetalert.css') }}" rel="stylesheet">
    <script src="{{ static('common/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ static('common/sweetalert/zlalert.js') }}"></script>

{#加载静态文件的方法，单独抽取为一个 宏（macro）#}
{#    优化前#}
{#    <link rel="stylesheet" href="{{ url_for('static',filename='cms/css/base.css') }}">#}
{#    <script src="{{ url_for('static',filename='cms/js/base.js') }}"></script>#}
{#    优化后#}
    <link rel="stylesheet" href="{{ static('cms/css/base.css') }}">
    <script src="{{ static('cms/js/base.js') }}"></script>
{#    <script src="{{ static('common/zlajax.js') }}"></script>#}
    <script src="{{ url_for('static',filename="common/zlajax.js") }}"></script>

    {#模板保留一个 block 用来存放 js 文件 #}
    {% block head %}

    {% endblock %}



</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">王者论坛管理后台</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
{#                <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}</a></li>#}
                <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">

                <input type="text" class="form-control" placeholder="查找...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>

                    <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
{#                判断当前用户是否有权限进行展示#}
{#                    {% if  g.cms_user.has_permission(CMPermission.POSTER) %}#}
                        <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
{#                    {% endif %}#}
                
{#                    {% if  g.cms_user.has_permission(CMPermission.COMMENTER) %}#}
                        <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
{#                    {% endif %}#}
                

{#                    {% if  g.cms_user.has_permission(CMPermission.BOARDER) %}#}
                        <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
{#                    {% endif %}#}

{#                    {% if  g.cms_user.has_permission(CMPermission.FRONTUSER) %}#}
                        <li class="nav-group user-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>

{#                    {% endif %}#}

{#                    {% if  g.cms_user.has_permission(CMPermission.CMSUSER) %}#}
                        <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
{#                    {% endif %}#}

{#                    {% if  g.cms_user.is_developer %}#}
                        <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>

{#                    {% endif %}#}

            </ul>
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <h1>{% block page_title %}

            {% endblock %}</h1>

            <div class="main_content">

                {% block main_content %}

                {% endblock %}

            </div>
        </div>
    </div>
</div>
</body>
</html>

zlbbs32/templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}
{%  from 'common/_macros.html' import static %}


{% block title %}
    板块管理
{% endblock %}

{% block page_title %}
    板块管理
{% endblock %}


{% block head %}
    <script src="{{ static('cms/js/boards.js') }}"></script>

{% endblock %}



{% block main_content %}

    <div class="top-box">

        <button class="btn btn-warning" style="float: right" id="add_board_btn">添加新板块</button>
    </div>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>板块名称</th>
            <th>帖子数量</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>

        <tbody>
                {% for board in boards %}
                    <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                        <td>{{ board.name }}</td>
                        <td>0</td>
                        <td>{{ board.creat_time }}</td>
                        <td>
                            <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                            <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
                        </td>

                    </tr>
                {% endfor %}



        </tbody>
    </table>








{% endblock %}

zlbbs32/templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}
{%  from 'common/_macros.html' import static %}


{% block title %}
    评论管理
{% endblock %}

{% block page_title %}
    评论管理
{% endblock %}


{% block head %}
    
{% endblock %}



{% block main_content %}
    
{% endblock %}

zlbbs32/templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}
{%  from 'common/_macros.html' import static %}


{% block title %}
    CMS组管理
{% endblock %}

{% block page_title %}
    CMS组管理
{% endblock %}


{% block head %}

{% endblock %}



{% block main_content %}

{% endblock %}

zlbbs32/templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}
{%  from 'common/_macros.html' import static %}


{% block title %}
    CMS用户管理
{% endblock %}

{% block page_title %}
    CMS用户管理
{% endblock %}


{% block head %}

{% endblock %}



{% block main_content %}

{% endblock %}

zlbbs32/templates/cms/cms_fusers.html
{% extends 'cms/cms_base.html' %}
{%  from 'common/_macros.html' import static %}


{% block title %}
    前台用户管理
{% endblock %}

{% block page_title %}
    前台用户管理
{% endblock %}


{% block head %}

{% endblock %}



{% block main_content %}

{% endblock %}

zlbbs32/templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block title %}
王者荣耀CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到王者荣耀CMS管理系统
{% endblock %}

zlbbs32/templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}
{%  from 'common/_macros.html' import static %}


{% block title %}
    帖子管理
{% endblock %}

{% block page_title %}
    帖子管理
{% endblock %}


{% block head %}

    <script src="{{ static('cms/js/posts.js') }}"></script>

{% endblock %}



{% block main_content %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>标题</th>
            <th>发布时间</th>
            <th>版块</th>
            <th>作者</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for post in all_post %}

{#            将每个帖子的信息及加精状态保存在 tr 标签里面，方便 js 进行获取，js 获取之后就知道是做加精操作，还是取消加精的操作#}
            <tr data-id={{ post.id }} data-highlight={{ 1 if post.highlight else 0 }}>
                <td><a target="_blank" href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a>
                </td>
                <td>{{ post.create_time }}</td>
                <td>{{ post.boards.name }}</td>
                <td>{{ post.author.username }}</td>
                <td>
                    {% if post.highlight %}
                        <button class="btn btn-info btn-xs highlight-btn">取消加精</button>
                    {% else %}
                        <button class="btn btn-danger btn-xs highlight-btn">加精</button>
                    {% endif %}
                    &nbsp;&nbsp;&nbsp;<button class="btn btn-default btn-xs">移除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}