zlbbs29/apps/front/models.py
# -*- coding: utf-8 -*-
from exts import db
import shortuuid
from datetime import datetime
import enum
from werkzeug.security import generate_password_hash,check_password_hash



class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4


class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(100), primary_key= True,default=shortuuid.uuid)
    telephone = db.Column(db.String(11), nullable=False, unique= True)
    username = db.Column(db.String(50),nullable=False)
    _password = db.Column(db.String(100),nullable=False)
    email = db.Column(db.String(50), unique= True)
    realname = db.Column(db.String(50))
    # 头像
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum),default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime,default=datetime.now)
    # 用户 与 帖子建立 一对多的关系
    posts = db.relationship('PostModel', backref='author')

    def __init__(self,*args,**kwargs):
        if 'password' in kwargs:
            self.password = kwargs.get('password')
            # 把 password 取出来之后，从 kwargs 中去掉
            kwargs.pop('password')
        super(FrontUser,self).__init__(*args,**kwargs)


    # password属性（方法）获取值
    @property
    def password(self):
        return self._password

    # password属性（方法）赋值
    @password.setter
    def password(self, rawpassword):
        self._password = generate_password_hash(rawpassword)

    def check_password(self,rawpassword ):
        result = check_password_hash(self.password,rawpassword)
        return result









if __name__ == '__main__':
    print
    1

zlbbs29/apps/front/forms.py
# -*- coding: utf-8 -*-
from wtforms import Form,StringField
from wtforms.validators import Regexp,EqualTo,ValidationError,InputRequired
from utils import zlmemcache



class SignupForm(Form):
    telephone=StringField(validators=[Regexp(r'1[3578]\d{9}',message='请输入正确格式的手机号码')])
    sms_captcha=StringField(validators=[Regexp(r'\w{4}',message='请输入四位短信验证码')])
    username=StringField(validators=[Regexp(r'.{3,15}',message='用户名长度在3-15位之间')])
    password=StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,15}',message='请输入正确格式的密码')])
    password2=StringField(validators=[EqualTo('password',message='两次输入的密码不一致')])
    graph_captcha=StringField(validators=[Regexp(r'\w{4}',message='图形验证码不正确')])


    # 验证某一个字段是否正确
    def validate_sms_captcha(self,field):
        sms_captcha = field.data
        telephone = self.telephone.data

        if sms_captcha != '1111':#测试用
            mem_sms_captcha = zlmemcache.get(telephone)
            if not mem_sms_captcha or mem_sms_captcha.lower() != sms_captcha.lower():
                raise ValidationError(message='短信验证码错误！')

    # 验证某一个字段是否正确
    def validate_graph_captcha(self,field):
        graph_captcha = field.data

        if graph_captcha != '1111':#测试用
            mem_graph_captcha = zlmemcache.get(graph_captcha.lower())
            if not mem_graph_captcha:
                raise ValidationError(message='图形验证码错误！')



class SigninForm(Form):
    telephone = StringField(validators=[Regexp(r'1[3578]\d{9}',message='请输入正确格式的手机号码')])
    password = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,15}',message='请输入正确格式的密码')])
    remember = StringField()



class AddPostForm(Form):
    title = StringField(validators=[InputRequired(message='请输入标题！')])
    content = StringField(validators=[InputRequired(message='请输入内容！')])
    board_id = StringField(validators=[InputRequired(message='请输入板块 id！')])


if __name__ == '__main__':
    print
    1

zlbbs29/apps/front/views.py
# -*- coding: utf-8 -*-
# from apps.front import bp
from flask import Blueprint,views,render_template,request,jsonify,session,url_for,g
from apps.front.forms import SignupForm,SigninForm,AddPostForm
from apps.models import BannersModel,BoardModel,PostModel
from apps.front.models import FrontUser
from apps.front.decorators import LoginRequired
from exts import alidayu,db
from utils import safeutils
import config
from flask_paginate import Pagination,get_page_parameter

front_bp = Blueprint('front',__name__)

# 测试：注册完成跳转回上一个页面
@front_bp.route('/test/')
def test():
    return render_template('test.html')


@front_bp.route('/')
def index():
    # 轮播图展示
    banners = BannersModel.query.order_by(BannersModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()
    # 分页前
    # posts = PostModel.query.all()

    # 分页后
    # 从 url 的查询参数获取当前是第几页(指定当前是第几页)
    page = request.args.get(get_page_parameter(),type=int,default=1)

    start = (page-1)*config.PER_PAGE
    end = start + config.PER_PAGE

    # 选中的板块
    bd = request.args.get('bd', type=int, default=None)
    total = 0
    # 获取指定页的数据
    if bd:
        posts = PostModel.query.filter_by(board_id=bd).slice(start,end)
        total = PostModel.query.filter_by(board_id=bd).count()
    else:
        posts = PostModel.query.slice(start, end)
        total = PostModel.query.count()

    # pagination 用于前台页面的上一页和下一页的控制
    pagination = Pagination(bs_version=3, page=page,total=total)


    # 返回多个参数到 html 页面
    context = {'banners':banners,
               'boards': boards,
               'posts': posts,
               'pagination':pagination,
               # 方便前端点击那个板块，那个板块就选中的参数
               'current_board':bd
               }


    return render_template('front/front_index.html',**context)

# 测试：短信验证测试接口(其他方面都正常，就接口有问题（appkey-not-exists），暂时放过)
# 阿里云账号：ali1010784344   密码：cwx364505

@front_bp.route('/sms_captcha/')
def sms_captcha():
    result = alidayu.send_sms('18735934287',code='abcd')
    if result:
        print('发送成功')
    else:
        print('发送失败')


# 发布帖子
@front_bp.route('/apost/',methods=['GET','POST'])
@LoginRequired
def apost():

    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html',boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data


            board = BoardModel.query.get(board_id)


            if not board:
                return jsonify({'code': '400', 'message': '没有这个板块！'})
            else:
                post = PostModel(title=title,content=content)
                post.boards = board
                # 帖子新增用户名
                post.author = g.front_user

                db.session.add(post)
                db.session.commit()

                return jsonify({'code': '200', 'message': '帖子发布成功！'})

        else:
            message = form.errors.popitem()[1][0]
            # 表单验证错误（数据格式不对）

            return jsonify({'code': '400', 'message': message})






class SignupView(views.MethodView):

    def get(self):
        # 获取上一个页面的 url
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html',return_to=return_to)
        else:
            return render_template('front/front_signup.html')
    def post(self):
        form = SignupForm(request.form)

        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password.data
            user = FrontUser(telephone=telephone,username=username,password=password)
            db.session.add(user)
            db.session.commit()

            return jsonify({'code': '200', 'message': '用户注册成功！'})
        else:

            message = form.errors.popitem()[1][0]
            # 表单验证错误（数据格式不对）

            return jsonify({'code': '400', 'message': message})


class SigninView(views.MethodView):

    def get(self):
        # 获取上一个页面的 url
        return_to = request.referrer
        # 不能跳转到本页面及注册页面
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(return_to):
            return render_template('front/front_signin.html',return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        password = form.password.data

        print(password)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remeber = form.remember.data

            print(password)

            user = FrontUser.query.filter_by(telephone=telephone).first()

            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remeber:
                    session.permanent = True
                return jsonify({'code': '200', 'message': '用户登录成功！'})
            else:

                return jsonify({'code': '400', 'message': '用户手机或者密码错误！'})
        else:
            message = form.errors.popitem()[1][0]
            # 表单验证错误（数据格式不对）
            return jsonify({'code': '400', 'message': message})







front_bp.add_url_rule('/signup/',view_func=SignupView.as_view('signup'))
front_bp.add_url_rule('/signin/',view_func=SigninView.as_view('signin'))

zlbbs29/templates/front/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>

    {% include "common/_head.html" %}
    <link href="{{ static('front/css/front_base.css') }}"rel="stylesheet">

    {% block head %}

    {% endblock %}

</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">王者论坛</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="请输入关键字">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

          {% if g.front_user %}
{#              优化后#}
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                {{g.front_user.username  }}
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="#">个人中心</a></li>
                <li><a href="#">设置</a></li>
                <li><a href="#">注销</a></li>

              </ul>
            </li>

          {% else %}
{#              优化前#}
              <li><a href="{{ url_for('front.signin') }}">登录</a></li>
              <li><a href="{{ url_for('front.signup') }}">注册</a></li>
          {% endif %}





      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="main-container">

    {% block body %}

    {% endblock %}
</div>


</body>
</html>

zlbbs29/templates/front/front_index.html
{% extends "front/front_base.html" %}
{% from "common/_macros.html" import static %}

{% block  title %}
王者荣耀论坛
{% endblock %}


{% block head %}

    <link href="{{ static('front/css/front_index.css') }}"rel="stylesheet">


{% endblock %}


{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
      <!-- 指示器 -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
      </ol>

      <!-- 轮播图 -->
      <div class="carousel-inner" role="listbox">

          {% for banner in banners %}
              {% if loop.first %}
                    <div class="item active">
              {% else %}
                    <div class="item">
              {% endif %}

              <a href="{{ banner.link_url }}"><img src="{{ banner.image_url }}" alt="..."></a>

        </div>
          {% endfor %}


      </div>

      <!-- 左右切换的控制按钮 -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>


    <div class="post-group">
           <ul class="post-group-head">
                    <li class="active"><a href="#">最新</a></li>

                    <li><a href="#">精华帖子</a></li>

                    <li><a href="#">点赞最多</a></li>

                    <li><a href="#">评论最多</a></li>

            </ul>

           <ul class="post-list-group">
                {% for post in posts %}
                    <li>
                        <div class="author-avatar-group">
{#                            如果用户没有上传头像就用默认的头像#}
                            <img src="{{ post.author.avatar or url_for('static',filename='common/images/logo.png') }}"
                                 alt="">
                        </div>

                        <div class="post-info-group">

                            <p class="post-title">{{ post.title }}</p>

                            <p class="post-info">
                                <span>作者:{{ post.author.username }}</span>
                                <span>发表时间:{{ post.create_time }}</span>
                                <span>评论:0</span>
                                <span>阅读数 :0</span>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>

        <div style="text-align: center">

            {{ pagination.links }}

        </div>


        </div>



    </div>

{#    所有板块#}
    <div class="sm-container">
        <div style="padding-bottom: 10px">
            <a href="{{ url_for('front.apost') }}" class="btn btn-warning btn-block">发布帖子</a>

        </div>

        <div class="list-group">

            {% if current_board %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}

            {% for board in boards %}
                {% if current_board == board.id %}
                <a href="{{ url_for('front.index',bd=board.id) }}" class="list-group-item active" >{{ board.name }}</a>
                {% else %}
                <a href="{{ url_for('front.index',bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
                {% endif %}
            {% endfor %}

        </div>

    </div>

{% endblock %}